package com.fundaro.zodiac.taurus.service.dto.dashboard;

public enum DashboardOperationType {
    LEGAL_ACCEPTANCE_REQUIRED,
    CALENDAR_AVAILABILITY_REQUIRED,
    CALENDAR_RESPONSES_MISSING,
    INVENTORY_DECISION_REQUIRED,
    INVENTORY_DECISIONS_PENDING,
    INVENTORY_RETURNS_PENDING,
    INVENTORY_ASSIGNMENTS_EXPIRING,
    FINANCE_MOVEMENTS_UNRECONCILED,
    NOTIFICATION_DELIVERY_FAILED
}
