version: "3"

services:

  mssql:
    container_name: taurus-mssql-container
    image: registry.gitlab.com/docker-archive/mssql-server-linux:latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pUk7gG6IC^6@"
      MSSQL_PID: "Express"
    ports:
      - 1434:1433
    networks:
      - taurus
    volumes:
      - ./mssql-data:/var/opt/mssql/data
    # user:
      # - taurus-user: 1GQKo$HxT6us8^z2

  mssqlscripts:
    container_name: taurus-mssqlscripts-container
    image: mssqlscript
    depends_on:
      - mssql
    networks:
      - taurus

  keycloak:
    container_name: taurus-keycloak-container
    image: quay.io/keycloak/keycloak:19.0.1
    restart: always
    environment:
      - KEYCLOAK_ADMIN=taurus-admin
      - KEYCLOAK_ADMIN_PASSWORD=96Dc_yTf9p5JF-0I7q"
      - DB_VENDOR=mssql
      - DB_USER=sa
      - DB_PASSWORD="pUk7gG6IC^6@"
      - DB_ADDR=mssql
      - DB_DATABASE=KEYCLOAK
      - KEYCLOAK_HTTP_PORT=8080
      # - KEYCLOAK_HTTPS=8443
      # - KEYCLOAK_HOSTNAME=tdo.synbrain.ai
    depends_on:
      - mssql
      - mssqlscripts
    ports:
      - 8081:8080
    networks:
      - taurus
    command: start-dev --db mssql --db-url-host mssql --db-url-database KEYCLOAK --db-username sa --db-password pUk7gG6IC^6@ --transaction-xa-enabled=false --features=token-exchange,declarative-user-profile --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
    volumes:
      - ./keycloak/data:/opt/keycloak/data
      - ./keycloak/themes:/opt/keycloak/themes

networks:
  taurus: {}

volumes:
  taurus-esdata:
    driver: local
