USE [master]
GO
/****** Object:  Database [KEYCLOAK]    Script Date: 20/08/2022 13:02:14 ******/
CREATE DATABASE [KEYCLOAK]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KEYCLOAK', FILENAME = N'/var/opt/mssql/data/KEYCLOAK.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'KEYCLOAK_log', FILENAME = N'/var/opt/mssql/data/KEYCLOAK_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KEYCLOAK].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [KEYCLOAK] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [KEYCLOAK] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [KEYCLOAK] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [KEYCLOAK] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [KEYCLOAK] SET ARITHABORT OFF 
GO
ALTER DATABASE [KEYCLOAK] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [KEYCLOAK] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [KEYCLOAK] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [KEYCLOAK] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [KEYCLOAK] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [KEYCLOAK] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [KEYCLOAK] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [KEYCLOAK] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [KEYCLOAK] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [KEYCLOAK] SET  ENABLE_BROKER 
GO
ALTER DATABASE [KEYCLOAK] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [KEYCLOAK] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [KEYCLOAK] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [KEYCLOAK] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [KEYCLOAK] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [KEYCLOAK] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [KEYCLOAK] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [KEYCLOAK] SET RECOVERY FULL 
GO
ALTER DATABASE [KEYCLOAK] SET  MULTI_USER 
GO
ALTER DATABASE [KEYCLOAK] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [KEYCLOAK] SET DB_CHAINING OFF 
GO
ALTER DATABASE [KEYCLOAK] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [KEYCLOAK] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [KEYCLOAK] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [KEYCLOAK] SET QUERY_STORE = OFF
GO
ALTER DATABASE [KEYCLOAK] SET  READ_WRITE 
GO