package com.fundaro.zodiac.taurus.domain;

import static com.fundaro.zodiac.taurus.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class NoticesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoticesAllPropertiesEquals(Notices expected, Notices actual) {
        assertNoticesAutoGeneratedPropertiesEquals(expected, actual);
        assertNoticesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoticesAllUpdatablePropertiesEquals(Notices expected, Notices actual) {
        assertNoticesUpdatableFieldsEquals(expected, actual);
        assertNoticesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoticesAutoGeneratedPropertiesEquals(Notices expected, Notices actual) {
        assertThat(expected)
            .as("Verify Notices auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoticesUpdatableFieldsEquals(Notices expected, Notices actual) {
        assertThat(expected)
            .as("Verify Notices relevant properties")
            .satisfies(e -> assertThat(e.getDeleted()).as("check deleted").isEqualTo(actual.getDeleted()))
            .satisfies(e -> assertThat(e.getInsertBy()).as("check insertBy").isEqualTo(actual.getInsertBy()))
            .satisfies(e ->
                assertThat(e.getInsertDate())
                    .as("check insertDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getInsertDate())
            )
            .satisfies(e -> assertThat(e.getEditBy()).as("check editBy").isEqualTo(actual.getEditBy()))
            .satisfies(e ->
                assertThat(e.getEditDate()).as("check editDate").usingComparator(zonedDataTimeSameInstant).isEqualTo(actual.getEditDate())
            )
            .satisfies(e -> assertThat(e.getUserId()).as("check userId").isEqualTo(actual.getUserId()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getMessage()).as("check message").isEqualTo(actual.getMessage()))
            .satisfies(e ->
                assertThat(e.getReadDate()).as("check readDate").usingComparator(zonedDataTimeSameInstant).isEqualTo(actual.getReadDate())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoticesUpdatableRelationshipsEquals(Notices expected, Notices actual) {
        // empty method
    }
}
