package com.fundaro.zodiac.taurus.domain;

import static com.fundaro.zodiac.taurus.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class TracksAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTracksAllPropertiesEquals(Tracks expected, Tracks actual) {
        assertTracksAutoGeneratedPropertiesEquals(expected, actual);
        assertTracksAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTracksAllUpdatablePropertiesEquals(Tracks expected, Tracks actual) {
        assertTracksUpdatableFieldsEquals(expected, actual);
        assertTracksUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTracksAutoGeneratedPropertiesEquals(Tracks expected, Tracks actual) {
        assertThat(expected)
            .as("Verify Tracks auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTracksUpdatableFieldsEquals(Tracks expected, Tracks actual) {
        assertThat(expected)
            .as("Verify Tracks relevant properties")
            .satisfies(e -> assertThat(e.getDeleted()).as("check deleted").isEqualTo(actual.getDeleted()))
            .satisfies(e -> assertThat(e.getInsertBy()).as("check insertBy").isEqualTo(actual.getInsertBy()))
            .satisfies(e ->
                assertThat(e.getInsertDate())
                    .as("check insertDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getInsertDate())
            )
            .satisfies(e -> assertThat(e.getEditBy()).as("check editBy").isEqualTo(actual.getEditBy()))
            .satisfies(e ->
                assertThat(e.getEditDate()).as("check editDate").usingComparator(zonedDataTimeSameInstant).isEqualTo(actual.getEditDate())
            )
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getComposer()).as("check composer").isEqualTo(actual.getComposer()))
            .satisfies(e -> assertThat(e.getArranger()).as("check arranger").isEqualTo(actual.getArranger()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTracksUpdatableRelationshipsEquals(Tracks expected, Tracks actual) {
        assertThat(expected)
            .as("Verify Tracks relationships")
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()));
    }
}
