# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: taurus
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
    networks:
      taurus-network:
        ipv4_address: 172.28.0.2
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
    networks:
      taurus-network:
        ipv4_address: 172.28.0.3
  rabbitmq:
    extends:
      file: ./rabbitmq.yml
      service: rabbitmq
    networks:
      taurus-network:
        ipv4_address: 172.28.0.4
#  backend:
#    image: fundanie/taurus-backend:1.0.0
#    container_name: backend-container
#    restart: unless-stopped
#    depends_on:
#      postgresql:
#        condition: service_healthy
#      keycloak:
#        condition: service_healthy
#      rabbitmq:
#        condition: service_started
#    networks:
#      taurus-network:
#        ipv4_address: 172.28.0.5
#  nginx:
#    image: fundanie/taurus-frontend:1.0.0
#    container_name: nginx-container
#    restart: unless-stopped
#    depends_on:
#      postgresql:
#        condition: service_healthy
#      keycloak:
#        condition: service_healthy
#      backend:
#        condition: service_healthy
#      rabbitmq:
#        condition: service_started
#    ports:
#      - 80:80
#      - 443:443
#    networks:
#      taurus-network:
#        ipv4_address: 172.28.0.6

networks:
  taurus-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
